language: node_js
dotnet: 1.0.3
dist: trusty
node_js:
  - "8"
script: 
  - mkdir /home/travis/build/vgaltes/CrystalGazer/test/testRepo/.git
  - npm test 
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      # - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-zesty-prod zesty main'
      #   key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
      - libstdc++-4.9-dev
      #- dotnet-dev-1.1.4