language: node_js
node_js:
  - "8"
script: 
  - mkdir /home/travis/build/vgaltes/CrystalGazer/test/testRepo/.git
  - npm test 
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev